fa=open(r'D:\ADOMBRA PROJECTS\ASMAP\ASMAP V1\ASMaP_v1.0_complete\asmap\frontend\admin.html','r',encoding='utf-8').read()
pos=fa.find('async function loadSetup')
print('--- Promise.all check ---')
print(repr(fa[pos:pos+350]))
print()
print('--- setup-periods HTML exists:', 'id="setup-periods"' in fa)
print('--- expandReport exists:', 'async function expandReport' in fa)
print('--- savePeriod exists:', 'async function savePeriod' in fa)
print('--- deletePeriod exists:', 'async function deletePeriod' in fa)
print('--- /admin/periods in fetch:', '/admin/periods' in fa)
print('--- report-by-class clickable:', 'expandReport' in fa)
